const APP_DATA = {
  "summary": {
    "practices": [
      {
        "name": "ERP Solutions",
        "head": "Amer Farghaly",
        "spoc": "Reham Ibrahim",
        "tasks": 0,
        "timeWithout": 0,
        "timeWith": 0,
        "timeSaved": 0,
        "efficiency": 0,
        "quality": 0,
        "completed": 0,
        "projects": 2
      },
      {
        "name": "CES",
        "head": "Osama Nagdy",
        "spoc": "Norah Al Wabel",
        "tasks": 7,
        "timeWithout": 286,
        "timeWith": 174.5,
        "timeSaved": 111.5,
        "efficiency": 60.0,
        "quality": 3.67,
        "completed": 6,
        "projects": 3
      },
      {
        "name": "BFSI",
        "head": "Mohab ElHaddad",
        "spoc": "Omar Ibrahim",
        "tasks": 28,
        "timeWithout": 140,
        "timeWith": 54.35,
        "timeSaved": 69.65,
        "efficiency": 52.2,
        "quality": 4.0,
        "completed": 26,
        "projects": 11
      },
      {
        "name": "EPS",
        "head": "Mohamed Ziaudin",
        "spoc": "Yousef Milhem",
        "tasks": 6,
        "timeWithout": 2.5,
        "timeWith": 0.01,
        "timeSaved": 0.49,
        "efficiency": 98.0,
        "quality": 4.0,
        "completed": 1,
        "projects": 2
      },
      {
        "name": "GRC",
        "head": "Ahmed Madkour",
        "spoc": "Mohamed Essam",
        "tasks": 6,
        "timeWithout": 30,
        "timeWith": 5.25,
        "timeSaved": 24.75,
        "efficiency": 84.7,
        "quality": 4.67,
        "completed": 6,
        "projects": 3
      },
      {
        "name": "EPCS",
        "head": "Mohamed Mobarak",
        "spoc": "Ahmed Shaheen",
        "tasks": 3,
        "timeWithout": 0,
        "timeWith": 0,
        "timeSaved": 0,
        "efficiency": 0,
        "quality": 4.67,
        "completed": 0,
        "projects": 4
      }
    ],
    "totals": {
      "tasks": 50,
      "timeWithout": 458.5,
      "timeWith": 234.11,
      "timeSaved": 206.39,
      "efficiency": 73.7,
      "quality": 4.2,
      "completed": 39,
      "projects": 25
    }
  },
  "tasks": [
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Miral Soliman ",
      "task": "product catalog ",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 2.0,
      "timeWith": 1.5,
      "timeSaved": 0.5,
      "efficiency": 0.25,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Miral Soliman ",
      "task": "Project scope questionnaire",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 4.0,
      "timeWith": 3.05,
      "timeSaved": 0.9500000000000002,
      "efficiency": 0.23750000000000004,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Gahada Bakry",
      "task": "HLD/FSD",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 6.0,
      "timeWith": 5.0,
      "timeSaved": 1.0,
      "efficiency": 0.16666666666666666,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 6.0,
      "timeWith": 1.4,
      "timeSaved": 4.6,
      "efficiency": 0.7666666666666666,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Database",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 2.0,
      "timeWith": 0.4,
      "timeSaved": 1.6,
      "efficiency": 0.8,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 4.0,
      "timeWith": 3.0,
      "timeSaved": 1.0,
      "efficiency": 0.25,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Database",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 2.0,
      "timeWith": 0.5,
      "timeSaved": 1.5,
      "efficiency": 0.75,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Code Review",
      "category": "Code Review",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 2.0,
      "timeWith": 1.5,
      "timeSaved": 0.5,
      "efficiency": 0.25,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Documentation",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 8.0,
      "timeWith": 6.5,
      "timeSaved": 1.5,
      "efficiency": 0.1875,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 4.0,
      "timeWith": 3.0,
      "timeSaved": 1.0,
      "efficiency": 0.25,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "1",
      "weekStart": "15/2/2026",
      "weekEnd": "19/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Database",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 2.0,
      "timeWith": 0.5,
      "timeSaved": 1.5,
      "efficiency": 0.75,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Miral Soliman ",
      "task": "",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Miral Soliman ",
      "task": "",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Gahada Bakry",
      "task": "",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 3.0,
      "timeWith": 0.5,
      "timeSaved": 2.5,
      "efficiency": 0.8333333333333334,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Database",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 3.0,
      "timeWith": 2.5,
      "timeSaved": 0.5,
      "efficiency": 0.16666666666666666,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 3.0,
      "timeWith": 1.0,
      "timeSaved": 2.0,
      "efficiency": 0.6666666666666666,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Code Review",
      "category": "Code Review",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 3.0,
      "timeWith": 2.0,
      "timeSaved": 1.0,
      "efficiency": 0.3333333333333333,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Documentation",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 2.0,
      "timeWith": 1.5,
      "timeSaved": 0.5,
      "efficiency": 0.25,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 3.0,
      "timeWith": 2.5,
      "timeSaved": 0.5,
      "efficiency": 0.16666666666666666,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Database",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 3.0,
      "timeWith": 1.0,
      "timeSaved": 2.0,
      "efficiency": 0.6666666666666666,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "6",
      "weekStart": "24/3/2026",
      "weekEnd": "26/3/2026",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "Omar Ibrahim ",
      "task": "Code Review",
      "category": "Code Review",
      "aiTool": "Claude",
      "prompt": "",
      "timeWithout": 8.0,
      "timeWith": 2.0,
      "timeSaved": 6.0,
      "efficiency": 0.75,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "6",
      "weekStart": "24/3/2026",
      "weekEnd": "26/3/2026",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 8.0,
      "timeWith": 6.0,
      "timeSaved": 2.0,
      "efficiency": 0.25,
      "quality": 0,
      "status": "Completed",
      "notes": "We used Copilot for identifying the steps and perquisites  for enabling HTTPS on WebLogic application server using .pfx certificates."
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Documentation",
      "category": "Documentation",
      "aiTool": "Claude",
      "prompt": "",
      "timeWithout": 8.0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": "Validating LLD sequence diagrams"
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "Project C-Personal Finance",
      "projectCode": "12135001",
      "employee": "AbdelRahman Badr Kamel",
      "task": "Code Review",
      "category": "Code Review",
      "aiTool": "Claude",
      "prompt": "",
      "timeWithout": 8.0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 7.0,
      "timeWith": 1.5,
      "timeSaved": 5.5,
      "efficiency": 0.7857142857142857,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Development",
      "category": "Development",
      "aiTool": "Claude",
      "prompt": "",
      "timeWithout": 10.0,
      "timeWith": 2.0,
      "timeSaved": 8.0,
      "efficiency": 0.8,
      "quality": 0,
      "status": "Completed",
      "notes": "Claude was significantly helpful regarding the infinity Visualizer UI tool "
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "Go Money MICRO FINANCE LENDING PLATFORM",
      "projectCode": "A1023401",
      "employee": "AL-Moataz Bellah Khamis Ahmed ",
      "task": "Code Review / Enhancements",
      "category": "Code Review / Enhancements",
      "aiTool": "Claude ",
      "prompt": "",
      "timeWithout": 4.0,
      "timeWith": 0.5,
      "timeSaved": 3.5,
      "efficiency": 0.875,
      "quality": 0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "ServiceNow",
      "projectCode": "Demand",
      "employee": "Omar Ibrahim ",
      "task": "HLD ",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 6.0,
      "timeWith": 2.0,
      "timeSaved": 4.0,
      "efficiency": 0.6666666666666666,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "7",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "CDF",
      "projectCode": "Demand",
      "employee": "Omar Ibrahim ",
      "task": "RFP",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 7.0,
      "timeWith": 1.0,
      "timeSaved": 6.0,
      "efficiency": 0.8571428571428571,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "8",
      "weekStart": "2026-05-04 00:00:00",
      "weekEnd": "2026-09-04 00:00:00",
      "project": "UCDE",
      "projectCode": "-",
      "employee": "Omar Ibrahim ",
      "task": "Experian Reverse engineering and FSD",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "Gave Copilot multiple old documentation to format in a readible business way and KT doecumentation",
      "timeWithout": 12.0,
      "timeWith": 2.0,
      "timeSaved": 10.0,
      "efficiency": 0.8333333333333334,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "BFSI \u2013 Weekly Aggregated Summary",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Metric",
      "weekStart": "Value",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Total Tasks Logged",
      "weekStart": "28",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Total Time Without AI (hrs)",
      "weekStart": "140",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Total Time With AI (hrs)",
      "weekStart": "54.35",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Total Time Saved (hrs)",
      "weekStart": "69.65",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Average Efficiency Gain %",
      "weekStart": "0.5215201465201467",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Average Quality Rating",
      "weekStart": "4",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Tasks Completed",
      "weekStart": "26",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "BFSI",
      "week": "Tasks In Progress",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "\u062a\u0637\u0648\u064a\u0631 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u062a\u0639\u0631\u064a\u0641\u064a \u0627\u0644\u0645\u0648\u062d\u062f \u0644\u0644\u0639\u0645\u0644\u0627\u0621",
      "projectCode": "53008701",
      "employee": "Ahmed Ibrahim",
      "task": "UI design for CRM form ",
      "category": "Development",
      "aiTool": "ChatGPT",
      "prompt": "Ask chatGPT to suggest for design based on customer requirements",
      "timeWithout": 8.0,
      "timeWith": 3.0,
      "timeSaved": 5.0,
      "efficiency": 0.625,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "\u062a\u0637\u0648\u064a\u0631 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u062a\u0639\u0631\u064a\u0641\u064a \u0627\u0644\u0645\u0648\u062d\u062f \u0644\u0644\u0639\u0645\u0644\u0627\u0621",
      "projectCode": "53008701",
      "employee": "Malak Madkour",
      "task": "code review",
      "category": "Code Review",
      "aiTool": "Github Copilot",
      "prompt": "Ask copilot to fix bugs",
      "timeWithout": 2.0,
      "timeWith": 0.5,
      "timeSaved": 1.5,
      "efficiency": 0.75,
      "quality": 5.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "\u062a\u0637\u0648\u064a\u0631 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u062a\u0639\u0631\u064a\u0641\u064a \u0627\u0644\u0645\u0648\u062d\u062f \u0644\u0644\u0639\u0645\u0644\u0627\u0621",
      "projectCode": "53008701",
      "employee": "Malak Madkour",
      "task": "auctions module development",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "Ask copilot to assist in model creation and mapping to CRM",
      "timeWithout": 4.0,
      "timeWith": 1.0,
      "timeSaved": 3.0,
      "efficiency": 0.75,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "2",
      "weekStart": "22/2/2026",
      "weekEnd": "26/2/2026",
      "project": "\u062a\u0637\u0648\u064a\u0631 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u062a\u0639\u0631\u064a\u0641\u064a \u0627\u0644\u0645\u0648\u062d\u062f \u0644\u0644\u0639\u0645\u0644\u0627\u0621",
      "projectCode": "53008701",
      "employee": "Fady Banoub",
      "task": "HTML and CSS web resources for UI design ",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "Ask copilot to assist in building CSS and HTML files",
      "timeWithout": 8.0,
      "timeWith": 2.0,
      "timeSaved": 6.0,
      "efficiency": 0.75,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "CES \u2013 Weekly Aggregated Summary",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Metric",
      "weekStart": "Value",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Total Tasks Logged",
      "weekStart": "7",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Total Time Without AI (hrs)",
      "weekStart": "286",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Total Time With AI (hrs)",
      "weekStart": "174.5",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Total Time Saved (hrs)",
      "weekStart": "111.5",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Average Efficiency Gain %",
      "weekStart": "0.600378787878788",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Average Quality Rating",
      "weekStart": "3.6666666666666665",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Tasks Completed",
      "weekStart": "6",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "CES",
      "week": "Tasks In Progress",
      "weekStart": "1",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "12",
      "weekStart": "29/3/2026",
      "weekEnd": "2026-02-04 00:00:00",
      "project": "RRM ERP Cloud Services Implementation 15/12/2025",
      "projectCode": "56000301",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "ERP \u2013 Weekly Aggregated Summary",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Metric",
      "weekStart": "Value",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Total Tasks Logged",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Total Time Without AI (hrs)",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Total Time With AI (hrs)",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Total Time Saved (hrs)",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Average Efficiency Gain %",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Average Quality Rating",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Tasks Completed",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "ERP",
      "week": "Tasks In Progress",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "1",
      "weekStart": "2026-04-12 00:00:00",
      "weekEnd": "16-04-2026",
      "project": "ANB EPS Corporate Module",
      "projectCode": "12150101",
      "employee": "",
      "task": "Providing Teams transcript to COPILOT prompt to generate MOM",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "Need to conduct a meeting with transcript and send it from teams to coplito to generate MOM",
      "timeWithout": 1.0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "2",
      "weekStart": "19-04-2026",
      "weekEnd": "23-04-2026",
      "project": "ANB EPS Corporate Module",
      "projectCode": "12150101",
      "employee": "",
      "task": "Provide Code / Script provided by the bank of their current system, provide it to the copilot prompt and get it in our solution language",
      "category": "Code Review",
      "aiTool": "Github Copilot",
      "prompt": "Having like JAVA script from the customer and try to analyze it",
      "timeWithout": 1.0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "3",
      "weekStart": "2026-05-04 00:00:00",
      "weekEnd": "2026-09-04 00:00:00",
      "project": "ANB EPS Corporate Module",
      "projectCode": "12150101",
      "employee": "",
      "task": "Ask Copilot prompt to generate SWIFT MT / MX samples for different message types",
      "category": "Testing",
      "aiTool": "Github Copilot",
      "prompt": "Asked the prompt to provide some samples of different types / different currencies / ...etc.",
      "timeWithout": 0.5,
      "timeWith": 0.01,
      "timeSaved": 0.49,
      "efficiency": 0.98,
      "quality": 4.0,
      "status": "Completed",
      "notes": "Whatever provided seems to be fine, any tuning is being provided is taken into consieration"
    },
    {
      "practice": "EPS",
      "week": "4",
      "weekStart": "2026-04-12 00:00:00",
      "weekEnd": "16-04-2026",
      "project": "Migration of TiPlus backend interfaces to MQ based MT & MX",
      "projectCode": "12158001",
      "employee": "",
      "task": "Test Data Generation and Preparation",
      "category": "Testing",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "5",
      "weekStart": "19-04-2026",
      "weekEnd": "23-04-2026",
      "project": "ANB EPS Corporate Module",
      "projectCode": "12150101",
      "employee": "",
      "task": "User Story Enhancement for Tester Readability",
      "category": "Testing",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "6",
      "weekStart": "26-04-2026",
      "weekEnd": "30-04-2026",
      "project": "Migration of TiPlus backend interfaces to MQ based MT & MX",
      "projectCode": "12158001",
      "employee": "",
      "task": "AI generates structured user guide content from scripts, process steps, and system descriptions, producing professional documentation drafts for review and refinement.",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "EPS \u2013 Weekly Aggregated Summary",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Metric",
      "weekStart": "Value",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Total Tasks Logged",
      "weekStart": "6",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Total Time Without AI (hrs)",
      "weekStart": "2.5",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Total Time With AI (hrs)",
      "weekStart": "0.01",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Total Time Saved (hrs)",
      "weekStart": "0.49",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Average Efficiency Gain %",
      "weekStart": "0.98",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Average Quality Rating",
      "weekStart": "4",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Tasks Completed",
      "weekStart": "1",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPS",
      "week": "Tasks In Progress",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "EPCS \u2013 Weekly Aggregated Summary",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Metric",
      "weekStart": "Value",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Total Tasks Logged",
      "weekStart": "3",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Total Time Without AI (hrs)",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Total Time With AI (hrs)",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Total Time Saved (hrs)",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Average Efficiency Gain %",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Average Quality Rating",
      "weekStart": "4.666666666666667",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Tasks Completed",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "EPCS",
      "week": "Tasks In Progress",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "1",
      "weekStart": "15/03/26",
      "weekEnd": "19/03/26",
      "project": "VAT Application Support",
      "projectCode": "12164301",
      "employee": "Yousef Elshabrawy",
      "task": "Resolving ORA-01555 Snapshot Too Old Error",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "What is ORA-01555: snapshot too old?",
      "timeWithout": 4.0,
      "timeWith": 0.5,
      "timeSaved": 3.5,
      "efficiency": 0.875,
      "quality": 5.0,
      "status": "Completed",
      "notes": "This ORA-01555 error means your long-running query needed older UNDO data, but Oracle had already overwritten it."
    },
    {
      "practice": "GRC",
      "week": "2",
      "weekStart": "22/03/26",
      "weekEnd": "26/03/26",
      "project": "VAT Application Support",
      "projectCode": "12164301",
      "employee": "Yousef Elshabrawy",
      "task": "SQL Query Optimization",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "Giving the query and asking about the performance tunning techniques I can use.",
      "timeWithout": 8.0,
      "timeWith": 2.0,
      "timeSaved": 6.0,
      "efficiency": 0.75,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "1",
      "weekStart": "15/03/26",
      "weekEnd": "19/03/26",
      "project": "ANB Change Request VAT Reconcilation",
      "projectCode": "12144401",
      "employee": "Umair Saleh",
      "task": "Converting Static MERGE PL/SQL to Dynamic MERGE PL/SQL",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "Optimization techniques for the procedures ",
      "timeWithout": 2.0,
      "timeWith": 0.25,
      "timeSaved": 1.75,
      "efficiency": 0.875,
      "quality": 5.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "2",
      "weekStart": "22/03/26",
      "weekEnd": "26/03/26",
      "project": "ANB Change Request VAT Reconcilation",
      "projectCode": "12144401",
      "employee": "Umair Saleh",
      "task": "SQL CASE to OR Condition Conversion",
      "category": "Development",
      "aiTool": "Github Copilot",
      "prompt": "Ask copilot to convert the query.",
      "timeWithout": 2.0,
      "timeWith": 0.25,
      "timeSaved": 1.75,
      "efficiency": 0.875,
      "quality": 5.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "3",
      "weekStart": "2026-05-04 00:00:00",
      "weekEnd": "2026-09-04 00:00:00",
      "project": "VAT Application Support",
      "projectCode": "12164301",
      "employee": "Yousef Elshabrawy",
      "task": "Drop multiple partitions dynamically from a daliy partitioned table",
      "category": "Database",
      "aiTool": "Github Copilot",
      "prompt": "How to drop multiple partitions from a daily paritioned table in Oracle?",
      "timeWithout": 2.0,
      "timeWith": 0.25,
      "timeSaved": 1.75,
      "efficiency": 0.875,
      "quality": 5.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "8",
      "weekStart": "2026-05-04 00:00:00",
      "weekEnd": "2026-09-04 00:00:00",
      "project": "UCDE",
      "projectCode": "-",
      "employee": "Ahmed Younis",
      "task": "Experian Reverse engineering and FSD",
      "category": "Documentation",
      "aiTool": "Github Copilot",
      "prompt": "Gave Copilot multiple old documentation to format in a readible business way and KT doecumentation",
      "timeWithout": 12.0,
      "timeWith": 2.0,
      "timeSaved": 10.0,
      "efficiency": 0.8333333333333334,
      "quality": 4.0,
      "status": "Completed",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "GRC \u2013 Weekly Aggregated Summary",
      "weekStart": "",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Metric",
      "weekStart": "Value",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Total Tasks Logged",
      "weekStart": "6",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Total Time Without AI (hrs)",
      "weekStart": "30",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Total Time With AI (hrs)",
      "weekStart": "5.25",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Total Time Saved (hrs)",
      "weekStart": "24.75",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Average Efficiency Gain %",
      "weekStart": "0.8472222222222222",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Average Quality Rating",
      "weekStart": "4.666666666666667",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Tasks Completed",
      "weekStart": "6",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    },
    {
      "practice": "GRC",
      "week": "Tasks In Progress",
      "weekStart": "0",
      "weekEnd": "",
      "project": "",
      "projectCode": "",
      "employee": "",
      "task": "",
      "category": "",
      "aiTool": "",
      "prompt": "",
      "timeWithout": 0,
      "timeWith": 0,
      "timeSaved": 0,
      "efficiency": 0,
      "quality": 0,
      "status": "",
      "notes": ""
    }
  ],
  "accomplishments": [
    {
      "id": "1",
      "date": "2026-02-28 00:00:00",
      "practice": "BFSI",
      "project": "Go Money",
      "projectCode": "",
      "spoc": "Omar Ibrahim",
      "employees": "Moemen Morsy/Al Moataz ibrahim",
      "title": "Full LMS Code Review & Remediation",
      "details": "Performed a comprehensive code review of the entire LMS codebase using GitHub Copilot. Identified critical code quality issues, security vulnerabilities, and performance bottlenecks. Applied AI-assisted code modifications and refactoring to improve maintainability, readability, and overall health of the codebase.",
      "aiTool": "Github Copilot",
      "category": "Code Review",
      "before": "Health Score: 2.5 / 10",
      "after": "Health Score: 6.8 / 10",
      "impact": "Health score improved by +4.3 (172% improvement)",
      "businessGains": "Client trust & confidence restored; reduced technical debt; improved code maintainability; strengthened delivery credibility",
      "cost": "Free of Cost",
      "effortSaved": "",
      "status": "Completed",
      "evidence": "",
      "notes": "First AI accomplishment logged for BFSI practice"
    },
    {
      "id": "2",
      "date": "2026-02-25 00:00:00",
      "practice": "EPCS",
      "project": "IT & Digital Transformation - Clarity Implementation",
      "projectCode": "C1009701",
      "spoc": "Ahmed Shaheen",
      "employees": "Eyad Ahmed / Menna Allah Ali ",
      "title": "AI\u2011assisted data migration validation & export",
      "details": "Built a Python Tkinter desktop application that automates end\u2011to\u2011end data migration prep. The app ingests .xlsx files, applies JSON\u2011based validation rules, highlights invalid rows with error reasons, enables in\u2011app corrections, and exports both an error report (.xlsx) and multiple import\u2011ready .csv batches (<=200 rows). Validation rules are configurable and reusable, reducing manual review, rework, and import delays.",
      "aiTool": "Github Copilot",
      "category": "Application Development",
      "before": "Cycle Time: 3.0 hrs per file",
      "after": "Cycle Time: 1.0 hr per file",
      "impact": "Time reduced from 3 hrs to 1 hr per file (\u20112 hrs, ~67% faster).",
      "businessGains": "Faster turnaround, fewer errors, standardized validation and batching.",
      "cost": "Free of Cost",
      "effortSaved": "2",
      "status": "Completed",
      "evidence": "Demo",
      "notes": "\u00a0"
    },
    {
      "id": "3",
      "date": "2026-05-03 00:00:00",
      "practice": "EPCS",
      "project": "ART - Alfresco DMS Production Support Services",
      "projectCode": "14005204",
      "spoc": "Ahmed AlSareti",
      "employees": "Omar GamalEldeen / \nAbdullah Al Duwaihi / Mahinour Emad Kadry",
      "title": "application development and configuration",
      "details": "add and configure HTTP-to-HTTPS proxy to Alfresco Kubernetes cluster to keep Elastisearch secured ",
      "aiTool": "Github Copilot",
      "category": "Application configuration",
      "before": "",
      "after": "",
      "impact": "Development and configuration time had been reduced from 8 hrs to 1 hr ",
      "businessGains": "Faser to finalize customer CR",
      "cost": "Free of Cost",
      "effortSaved": "8",
      "status": "testing",
      "evidence": "",
      "notes": ""
    },
    {
      "id": "4",
      "date": "15/3/2026",
      "practice": "EPCS",
      "project": "DMS Activities",
      "projectCode": "51014108-001",
      "spoc": "Ahmed AlSareti",
      "employees": "Omar GamalEldeen / \nAbdullah Al Duwaihi / Mahinour Emad Kadry",
      "title": "application development",
      "details": "update Alfresco workspace front-end application (Angular) to allow search by metadata",
      "aiTool": "Github Copilot",
      "category": "Application Development",
      "before": "",
      "after": "",
      "impact": "Development and configuration time had been reduced from 1 week to 2 days ",
      "businessGains": "enhance internal web applications development",
      "cost": "Free of Cost",
      "effortSaved": "",
      "status": "Completed",
      "evidence": "https://github.com/ejadasa-copilot-business/alfresco-digital-workspace",
      "notes": ""
    }
  ],
  "copilotUsers": [
    {
      "practice": "BFSI",
      "name": "Ibrahim Amin ",
      "email": "iamin@ejada.com    ",
      "skill": "Developer Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Omar Ghazalah",
      "email": "oghazalah@ejada.com",
      "skill": "Developer Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Omar Ibrahim ",
      "email": "oibrahim@ejada.com",
      "skill": "Solution Architect ",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Amr Akady",
      "email": "amr.alkady@ejada.com",
      "skill": "Solution Architect ",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Miral Soliman ",
      "email": "miral.soliman@ejada.com",
      "skill": "Business Analyst",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Gahada Bakry",
      "email": "gbakry@ejada.com",
      "skill": "Business Analyst",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Bassem Nasr ",
      "email": "basim.nasir@ejada.com",
      "skill": "LEAD BUSINESS ARCHITECT",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Mohammed Omar Eid",
      "email": "moeid@ejada.com",
      "skill": "Senior Enterprise Architect",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Islam Mohamed",
      "email": "imohamed@ejada.com",
      "skill": "Analyst/Senior Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Nourane Elkhawalka",
      "email": "nelkhawalka@ejada.com",
      "skill": "Delivery Manager",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Sabreen AbdElmaguid",
      "email": "sabdelmaguid@ejada.com",
      "skill": "Developer Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Youssuf Elshayeb ",
      "email": "yelshayeb@ejada.com\u00a0",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Farah Hassaan ",
      "email": "fhassaan@ejada.com\u00a0",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Moustafa Daebis ",
      "email": "mdaebis@ejada.com\u00a0",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Seif Eldin Amr ",
      "email": "seifeldin.amr@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "AL-Moataz Bellah Khamis Ahmed ",
      "email": "abellah@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Nour Eldin Hazem Abdelsalam",
      "email": "nhabdelsalam@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Yara Elmelegy  ",
      "email": "yelmelegy@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Rafeef Alsealo",
      "email": "ralsealo@ejada.com",
      "skill": "Business Analyst",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Abdulrahman Alafandy",
      "email": "aalafandy@ejada.com",
      "skill": "Technical Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Ahmed Said Mohamed ",
      "email": "amsaid@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Mariam Elshimi ",
      "email": "melshimi@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Manar Elsayed ",
      "email": "maelsayed-v@ejada.com",
      "skill": "Developer",
      "remarks": "pending"
    },
    {
      "practice": "BFSI",
      "name": "Maram Motaz ",
      "email": "mmotaz@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Ahmad Nouh",
      "email": "anouh@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Farah Elgendy                  ",
      "email": "felgendy@ejada.com      ",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Salma Ahmed Abdelsalam Mostafa ",
      "email": "salma.ahmed@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Ziad Elkhazendar               ",
      "email": "zelkhazendar@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Ingy Ibrahim                   ",
      "email": "iibrahim@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Hossam Gamal Abdelhaleem",
      "email": "hgamal@ejada.com",
      "skill": "Technical Project Manager",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Amr Nady",
      "email": "anady@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Ahmed Elsahamy",
      "email": "aelsahlamy@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Ahmad Elkilany",
      "email": "aelkilany@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "AbdelRahman Badr Kamel",
      "email": "abadr@ejada.com",
      "skill": "Technical Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Marry Waseem",
      "email": "mwaseem@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Abdelrahman Mohamed Khalil",
      "email": "amkhalil@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Mohammed Abdulelah Al Harbi",
      "email": "maalharbi@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Yahia Zaky",
      "email": "yzaky@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Youmna Elmezyn",
      "email": "yelmezyn@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Hakeemah Alharbi",
      "email": "halharbi@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "BFSI",
      "name": "Osama Alhasson",
      "email": "oalhasson@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "CES",
      "name": "Ahmed Ibrahim",
      "email": "aibrahim@ejada.com",
      "skill": "Technical Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "GRC",
      "name": "Maisam Ali",
      "email": "maisam@ejada.com",
      "skill": "Project Manager",
      "remarks": "access granted"
    },
    {
      "practice": "GRC",
      "name": "Umair Saleh",
      "email": "usaleh@ejada.com",
      "skill": "Data Engineer",
      "remarks": "access granted"
    },
    {
      "practice": "GRC",
      "name": "Yousef Elshabrawy",
      "email": "yelshabrawy@ejada.com",
      "skill": "Software Engineer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Reham Ibrahim",
      "email": "rmibrahim@ejada.com",
      "skill": "Development / Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "AmerFarghaly",
      "email": "afarghaly@ejada.com",
      "skill": "ERP unit Manager",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Osama Yehia Mohamed Mohamed Awad",
      "email": "oyehia@ejada.com",
      "skill": "Functional / Sr. Associate",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Salma Saeed Mahmoud Gharib ",
      "email": "sgharib@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mohamed Ayman Said Mahmoud ",
      "email": "masaid@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Waleed Mostafa Abdelhalem Ali",
      "email": "awkhalifa@ejada.com",
      "skill": "Functional / Sr. Associate",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Reda Abdullah Elsayed Abdelmalak ElMekawy",
      "email": "relmekawy@ejada.com",
      "skill": "Development / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mohamed Saad Ali Ali Elazaly",
      "email": "mselazaly@ejada.com",
      "skill": "Development / Sr. Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mohamed Emad Ahmed Mansour Mohamed Mansour",
      "email": "memansour@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Nour Mahmoud Ali Mahmoud Nafady",
      "email": "nour.nafady@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Nada Ali Hassan Ahmed Abdelrahim",
      "email": "nada.abdelrahim@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Khaled Ossama Abdelrahman Mohamed Abouelella",
      "email": "kossama@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "IBRAHIM HASSAN ABDELSAMAD ZAYED",
      "email": "izayed@ejada.com",
      "skill": "DBA / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Doaa Mohamed Mohamed Mostafa",
      "email": "doaa.mostafa@ejada.com",
      "skill": "Development / Sr. Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MAHMOUD NAEL ABDULLAH DRAIDI",
      "email": "mdraidi@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "TARIQ MOHAMMED S ALNASYAN",
      "email": "talnasyan@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MANAR EMAD F ALSHAREEF",
      "email": "malshareef@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MAHA HMOUD M ALAAMRI",
      "email": "maha.alaamri@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "RENAD SAEED S ALSHEHRI",
      "email": "ranad.alshehri@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "HANIN KHALID M ALSHAMRANI",
      "email": "halshamrani@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mahmoud Ahmed Mohamed Hussein Shalaby",
      "email": "mshalaby@ejada.com",
      "skill": "Functional / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Hossam Fahim Abdelhakeem Mohamed",
      "email": "hfmohamed@ejada.com",
      "skill": "Functional / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ADEL MOHAMED AHMED MOHAMED",
      "email": "aamohamed@ejada.com",
      "skill": "Functional / Sr. Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Abdelrahman Hatem Metwally Mahmoud ",
      "email": "ametwally@ejada.com",
      "skill": "Development / Sr. Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMMED KHALIFAH SAEED BAHNASAWI",
      "email": "mkhalifah@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ADEL ELSAID MOHAMED MOUSTAFA",
      "email": "aelsaid@ejada.com",
      "skill": "Functional / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "HAITHAM HANI AHMED MAAMOUN SALLAM",
      "email": "hsallam@ejada.com",
      "skill": "Functional / Sr. Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ELSAYED ISMAEL ELSAYED MOHAMED IBRAHIM",
      "email": "eismail@ejada.com",
      "skill": "Management",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Omar Ragab Hassan Salem",
      "email": "osalem@ejada.com",
      "skill": "Functional / Sr. Associate",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMED ABD ELKHALEK ELSAKA IBRAHIIM",
      "email": "melsaka@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "HAYTHAM MOHAMED ABDELHAMID ELSAYED",
      "email": "helsayed@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Islam Zaki",
      "email": "islam.zaki@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Salma Yousry AbdElmetal \u00a0Amin ",
      "email": "syabdelmetal@ejada.com",
      "skill": "Development / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Hossam Wally Ibrahim Wally",
      "email": "hossam.wally@ejada.com",
      "skill": "Development / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Shaimaa Molouk Mohamed Ibrahim Abdallah",
      "email": "shaimaa.abdallah@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOSTAFA MOHARRAM ABDEL LATIF GHOBASHY",
      "email": "mghobashy@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMMED OMAR MOHAMMED ALBALKHI",
      "email": "Malbalkhi@ejada.com",
      "skill": "Development / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "IBRAHEEM FAYAK IBRAHEEM HASAN",
      "email": "ifhassan@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "NIJAMUDEEN SHIEK ALAWUDEEN",
      "email": "nalawudeen@ejada.com",
      "skill": "Development / Sr. Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ABDULELAH HADYAN H ALTHUWAYBI",
      "email": "aalthuwaybi@ejada.com",
      "skill": "Development / Sr. Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ABDULAZIZ AHMED A ALANAZI",
      "email": "aaalanazi@ejada.com",
      "skill": "Development / Sr. Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMMED SAEED RAJAB SHABAAN",
      "email": "mshaaban@ejada.com",
      "skill": "Development / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMMAD SAYED AHMED HAMMAM",
      "email": "mhamam@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Ibrahim Ahmed Ali Kotb",
      "email": "akotb@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "HOSSAM FARAJ MOHAMED ABDELMEGUID",
      "email": "hmohammed@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "HASSAN HUSSEIN ABDALLAH MANTAWY",
      "email": "hmantawy@ejada.com",
      "skill": "Functional / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MUSTAFA MOHAMED SHEHATA RADWAN",
      "email": "mostafa@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mohamed Hassan Abdelaziz Sallam",
      "email": "msallam@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "TAHER MOHAMED ELSAID MESBAH",
      "email": "telsaaed@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ranim Mahmoud Ahmed ElShafie ",
      "email": "rmelshafie@ejada.com",
      "skill": "Development / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mostafa Fathy Abdelwahab Mohamed Emara",
      "email": "memara@ejada.com",
      "skill": "Development / Sr. Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Sama Abdullah Zakaria AboAlnaja",
      "email": "szakaria@ejada.com",
      "skill": "Development / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Abdallah Ibrahim Abdullah Othman Saleh",
      "email": "aisaleh@ejada.com",
      "skill": "Development / Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Islam Ahmed Mohamed Hassanin",
      "email": "ihassanin@ejada.com",
      "skill": "Development / Sr. Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Omar Magdy",
      "email": "oabdelhameed@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Elmissiry",
      "email": "aelmissiry@ejada.com",
      "skill": "Development / Team Leader",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "AHMED ABDUL HAMEED RAGAB ABDEL HAMID",
      "email": "aabdelhamid@ejada.com",
      "skill": "Functional / SME",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMMED MAHMOUD AHMED SAYED EL ESAWEE",
      "email": "melesawee@ejada.com",
      "skill": "Functional / SME",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "MOHAMMED IBRAHIM MOHAMMED GHAZI",
      "email": "mabdelmegid@ejada.com",
      "skill": "Functional / SME",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Hamed Mohamed Farag",
      "email": "hmfarag@ejada.com",
      "skill": "Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mahmoud Ali Mohamed kamal",
      "email": "mkamal@ejada.com",
      "skill": "Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mahmoud Abdrabou",
      "email": "mabdrabo@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Islam Sobhy Mohamed",
      "email": "iahmed@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Nourhan AlSaud",
      "email": "nalsaud@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Omar Ahmed Abd Al-Azeem",
      "email": "oabdrabou@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mahmoud Ahmed Ragabe ",
      "email": "maragabe@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Alaa Shaker Elbadry",
      "email": "aashaker@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Mohamed Mahmoud  Mohamed Hassan Radwan",
      "email": "mradwan@ejada.com",
      "skill": "Functional / Senior Associate",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Reham Ibrahim mohamed Ibrahim Mohamed",
      "email": "rmibrahim@ejada.com",
      "skill": "Development / Senior Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ABDULLAH HUSSAIN T BO ZAID",
      "email": "abozaid@ejada.com ",
      "skill": "Development / Associate Software Engineer ",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "FATIMAH HUSSAIN A ALDAGDOUG",
      "email": "faldagdoug@ejada.com",
      "skill": "Development / Software Engineer ",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Mohamed Ibrahim Saber ",
      "email": "amsaber@ejada.com",
      "skill": "Management",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "TANWEER ZAKI",
      "email": "tzaki@ejada.com",
      "skill": "Development / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Ibrahim Ibrahim Abdelmotaleb Tortor",
      "email": "atortor@ejada.com",
      "skill": "Functional / Senior Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed Abdelaziz Ragab Sheta ",
      "email": "aaragab@ejada.com",
      "skill": "Technical / Senior Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "FATMEH WAGEEH MEIRZA AL SAIF",
      "email": "falsaif@ejada.com",
      "skill": "Development / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "SALEH ABDULLAH AL MAHROUS",
      "email": "salmahrous@ejada.com",
      "skill": "Development / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "HUSAIN ALI IBRAHIM ALSALEM",
      "email": "halsalem@ejada.com",
      "skill": "Development / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Rami Rabea Mohamed Ali",
      "email": "rali@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ELSAYED SALAHELDIN ABOUD MAHMOUD ELMAWY",
      "email": "eelmawy@ejada.com",
      "skill": "Functional / Principal",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "ABDULLAH MOHAMED MOHAMED HAMED",
      "email": "ahamed@ejada.com",
      "skill": "Functional / Senior Team Lead",
      "remarks": "access granted"
    },
    {
      "practice": "ERP",
      "name": "Ahmed El Sharqawy",
      "email": "aelsharkawy@ejada.com",
      "skill": "Functional / Consultant",
      "remarks": "access granted"
    },
    {
      "practice": "GRC",
      "name": "Maisam Ali",
      "email": "maisam@ejada.com",
      "skill": "Project Manager",
      "remarks": "access granted"
    },
    {
      "practice": "GRC",
      "name": "Yousef El Shabrawy",
      "email": "yelshabrawy@ejada.com",
      "skill": "Support Engineer",
      "remarks": "access granted"
    },
    {
      "practice": "GRC",
      "name": "Umair Saleh Muhammad",
      "email": "usaleh@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "CES",
      "name": "Malak Madkour",
      "email": "mmadkour@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "CES",
      "name": "Mohamed Mohsen",
      "email": "mohamed.madboly@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "CES",
      "name": "Mostafa Khaled",
      "email": "mostafa.zayed@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "CES",
      "name": "Fady Banoub",
      "email": "fbanoub@ejada.com",
      "skill": "Developer",
      "remarks": "access granted"
    },
    {
      "practice": "",
      "name": "Q1980",
      "email": "ahmed.farag@ejada.com",
      "skill": "",
      "remarks": ""
    },
    {
      "practice": "",
      "name": "Q1774",
      "email": "bbassant@ejada.com",
      "skill": "",
      "remarks": ""
    },
    {
      "practice": "",
      "name": "Q0458",
      "email": "kibrahim@ejada.com",
      "skill": "",
      "remarks": ""
    },
    {
      "practice": "",
      "name": "Q2186",
      "email": "ahmed.morsy@ejada.com",
      "skill": "",
      "remarks": ""
    },
    {
      "practice": "",
      "name": "Q2009",
      "email": "noibrahim@ejada.com",
      "skill": "",
      "remarks": ""
    },
    {
      "practice": "",
      "name": "U0024",
      "email": "ogfathy@ejada.com",
      "skill": "",
      "remarks": ""
    },
    {
      "practice": "BFSI",
      "name": "Manar Elsayed\u00a0",
      "email": "maelsayed-v@ejada.com",
      "skill": "Developer",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Ramy moustafa",
      "email": "mramy@ejada.com",
      "skill": "Technical Team Lead",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Eslam Khattab",
      "email": "ekhattab@ejada.com",
      "skill": "sloution architect",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Haguar Dessouky",
      "email": "hdessouky@ejada.com",
      "skill": "CRM Developer",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Omar Nour",
      "email": "onour@ejada.com",
      "skill": "CRM Developer",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Nada Gaafar",
      "email": "ngaafar@ejada.com",
      "skill": "CRM Developer",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Omar Amir Youssef",
      "email": "oayoussef@ejada.com",
      "skill": "CRM Developer",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Mohamed Ghoz",
      "email": "mghoz@ejada.com",
      "skill": "CRM Setup Admin",
      "remarks": ""
    },
    {
      "practice": "CES",
      "name": "Mishary Al Jarie",
      "email": "maljarie@ejada.com",
      "skill": "CRM Setup Admin",
      "remarks": ""
    },
    {
      "practice": "BFSI",
      "name": "Hossam Shaybon",
      "email": "\u00a0hshaybon@ejada.com",
      "skill": "Developer\u00a0",
      "remarks": ""
    },
    {
      "practice": "BFSI",
      "name": "Ayman Sayed",
      "email": "ayman.sayed@ejada.com",
      "skill": "BFSI Delivery Manager",
      "remarks": ""
    },
    {
      "practice": "",
      "name": "Ahmed Younis",
      "email": "",
      "skill": "",
      "remarks": ""
    }
  ],
  "projects": [
    {
      "practice": "BFSI",
      "projectCode": "12135001",
      "contractNumber": "KSA-25-0123",
      "customer": "Al Rajhi Bank",
      "contractValue": 7420000.0,
      "startDate": "2025-01-23 00:00:00",
      "endDate": "2025-09-30 00:00:00",
      "projectName": "Project C-Personal Finance",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E1919 - Youssef Mohamed Yousef Salah (ymyoussef)"
    },
    {
      "practice": "BFSI",
      "projectCode": "A1023401",
      "contractNumber": "KSA-25-0319",
      "customer": "Etihad GO Telecom Company",
      "contractValue": 2250000.0,
      "startDate": "2025-05-08 00:00:00",
      "endDate": "2026-02-15 00:00:00",
      "projectName": "Go Money MICRO FINANCE LENDING PLATFORM",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "Q1981 - Sarah Ali Mohamed El Mansoury (selmansoury)"
    },
    {
      "practice": "ERP",
      "projectCode": "56000301",
      "contractNumber": "KSA-25-0797",
      "customer": "Remat Al-Riyadh",
      "contractValue": 14941795.65,
      "startDate": "2025-12-15 00:00:00",
      "endDate": "2027-06-30 00:00:00",
      "projectName": "RRM ERP Cloud Services Implementation",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "A0038: Mohamed Abdul Aziz Khaleel"
    },
    {
      "practice": "ERP",
      "projectCode": "C1007201",
      "contractNumber": "",
      "customer": "ITSM",
      "contractValue": 0,
      "startDate": "",
      "endDate": "",
      "projectName": "ITSM Project",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": ""
    },
    {
      "practice": "GRC",
      "projectCode": "12164301",
      "contractNumber": "",
      "customer": "",
      "contractValue": 0,
      "startDate": "2025-12-01 00:00:00",
      "endDate": "2026-11-30 00:00:00",
      "projectName": "VAT Application Support",
      "revenueType": "TM",
      "lineType": "External",
      "projectManager": "Maisam Ali"
    },
    {
      "practice": "GRC",
      "projectCode": "12144401",
      "contractNumber": "",
      "customer": "",
      "contractValue": 0,
      "startDate": "2025-06-01 00:00:00",
      "endDate": "2026-06-01 00:00:00",
      "projectName": "ANB Change Request VAT Reconcilation",
      "revenueType": "Fixed Price",
      "lineType": "External",
      "projectManager": "Maisam Ali"
    },
    {
      "practice": "GRC",
      "projectCode": "12154701",
      "contractNumber": "",
      "customer": "",
      "contractValue": 0,
      "startDate": "2024-09-15 00:00:00",
      "endDate": "2026-09-30 00:00:00",
      "projectName": "ANB Consumer Loans Historical Reconcilation",
      "revenueType": "Fixed Price",
      "lineType": "External",
      "projectManager": "Maisam Ali"
    },
    {
      "practice": "CES",
      "projectCode": "62002301",
      "contractNumber": "KSA-23-0238",
      "customer": "Ministry of Health",
      "contractValue": 9750013.0,
      "startDate": "2023-04-01 00:00:00",
      "endDate": "31-12-2026",
      "projectName": "MOH - Portals Support & Management",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "S0013 - Simon Jiries Istefan Salameh (ssalameh)"
    },
    {
      "practice": "CES",
      "projectCode": "",
      "contractNumber": "KSA-25-0854",
      "customer": "Zakat, Tax and Customs Authority",
      "contractValue": 2608600.0,
      "startDate": "2025-04-12 00:00:00",
      "endDate": "30-09-2027",
      "projectName": "\u062a\u0637\u0648\u064a\u0631 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u062a\u0639\u0631\u064a\u0641\u064a \u0627\u0644\u0645\u0648\u062d\u062f \u0644\u0644\u0639\u0645\u0644\u0627\u0621",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E0546 - Mohammed Mustafa Mohammed El Marasy (melmarasy)"
    },
    {
      "practice": "CES",
      "projectCode": "23045701",
      "contractNumber": "KSA-25-0718",
      "customer": "Tawtheeq Company for Registering Financial Lease Contracts",
      "contractValue": 600000.0,
      "startDate": "30-11-2025",
      "endDate": "2026-01-09 00:00:00",
      "projectName": "tawtheeq service now crm",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E2048 - Salah Shahat Hassanin Elayat (selayat)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13011901",
      "contractNumber": "KSA-25-0532",
      "customer": "Emkan Finance Company",
      "contractValue": 1890000.0,
      "startDate": "2025-01-09 00:00:00",
      "endDate": "31-12-2025",
      "projectName": "Emkan E-Commerce",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E3046 - Mohammad Abdul Muttalib Khan (akhan)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13012401",
      "contractNumber": "KSA-25-0500",
      "customer": "Emkan Finance Company",
      "contractValue": 2070000.0,
      "startDate": "20-10-2025",
      "endDate": "31-05-2026",
      "projectName": "Emkan Freelance",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E3046 - Mohammad Abdul Muttalib Khan (akhan)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13012501",
      "contractNumber": "KSA-25-0597",
      "customer": "Emkan Finance Company",
      "contractValue": 2310000.0,
      "startDate": "2025-01-10 00:00:00",
      "endDate": "31-05-2026",
      "projectName": "Emkan Revamp",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E2994 - Ahmed\u00a0 Ali Abdelaziz Ismail Khater (ahmed.khater)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13005301",
      "contractNumber": "KSA-24-0094",
      "customer": "Emkan Finance Company",
      "contractValue": 44776400.0,
      "startDate": "18-03-2024",
      "endDate": "31-12-2025",
      "projectName": "Emkan - BNPL Implementation (LMS + LOS)",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E3046 - Mohammad Abdul Muttalib Khan (akhan)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13008001",
      "contractNumber": "KSA-24-0317",
      "customer": "Emkan Finance Company",
      "contractValue": 8100000.0,
      "startDate": "18-08-2024",
      "endDate": "31-12-2025",
      "projectName": "Emkan - Apple Project Implementation",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E2584 - Waleed Mohamed Amin Elsaid Abdelhamid Saleh (wsaleh)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13008101",
      "contractNumber": "KSA-24-0447",
      "customer": "Emkan Finance Company",
      "contractValue": 11895902.0,
      "startDate": "2024-08-10 00:00:00",
      "endDate": "2025-01-10 00:00:00",
      "projectName": "Emkan - SME Product Suite Implementation (B2B)",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E1915 - Mohab Mahmoud Kamel Elhadad (melhadad)"
    },
    {
      "practice": "BFSI",
      "projectCode": "13013201",
      "contractNumber": "KSA-25-0675",
      "customer": "Emkan Finance Company",
      "contractValue": 1601419.0,
      "startDate": "2025-09-11 00:00:00",
      "endDate": "2026-08-02 00:00:00",
      "projectName": "EMKAN Vulnerability Report",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E1534 - Fathy Ahmed Shehata Khattab (fkhatab)"
    },
    {
      "practice": "BFSI",
      "projectCode": "A1023401",
      "contractNumber": "KSA-25-0319",
      "customer": "Etihad GO Telecom Company",
      "contractValue": 2250000.0,
      "startDate": "2025-08-05 00:00:00",
      "endDate": "15-02-2026",
      "projectName": "Go Money MICRO FINANCE LENDING PLATFORM",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "Q1981 - Sarah Ali Mohamed El Mansoury (selmansoury)"
    },
    {
      "practice": "BFSI",
      "projectCode": "94000802",
      "contractNumber": "KSA-24-0304",
      "customer": "Tourism Development Fund",
      "contractValue": 5130400.0,
      "startDate": "2024-11-08 00:00:00",
      "endDate": "2026-11-08 00:00:00",
      "projectName": "TDF Transact Support and Enhancement - Temenos T24",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "Q1981 - Sarah Ali Mohamed El Mansoury (selmansoury)"
    },
    {
      "practice": "BFSI",
      "projectCode": "94000601",
      "contractNumber": "KSA-23-0116",
      "customer": "Tourism Development Fund",
      "contractValue": 3478000.0,
      "startDate": "26-09-2023",
      "endDate": "19-06-2025",
      "projectName": "TDF - Risk Monitoring and Reporting Portal",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "Q1981 - Sarah Ali Mohamed El Mansoury (selmansoury)"
    },
    {
      "practice": "Payments Solutions",
      "projectCode": "12158001",
      "contractNumber": "",
      "customer": "ANB",
      "contractValue": 490000.0,
      "startDate": "2025-09-22 00:00:00",
      "endDate": "2026-06-30 00:00:00",
      "projectName": "Migration of TiPlus backend interfaces to MQ based MT & MX",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E2195 - HASEEB ULLAH KHAN"
    },
    {
      "practice": "Payments Solutions",
      "projectCode": "12150101",
      "contractNumber": "",
      "customer": "ANB",
      "contractValue": 2688760.0,
      "startDate": "2025-05-30 00:00:00",
      "endDate": "2026-12-01 00:00:00",
      "projectName": "ANB EPS Corporate Module",
      "revenueType": "Fixed Price",
      "lineType": "Internal",
      "projectManager": "E2195 - HASEEB ULLAH KHAN \u00a0"
    }
  ],
  "lovs": {
    "taskCategories": [
      "Development",
      "Database",
      "Documentation",
      "Testing",
      "Code Review"
    ],
    "aiTools": [
      "Github Copilot",
      "Cursor",
      "Codex",
      "Claude",
      "ChatGPT",
      "Gemini"
    ]
  }
};
