#!/bin/bash
# ============================================================
# EAS AI Dashboard - Deploy Approval Workflow Migration
# Run this script to apply the SQL migration to Supabase
# ============================================================

echo "🔧 EAS AI Approval Workflow - Deployment Guide"
echo "=================================================="
echo ""
echo "⚠️  IMPORTANT: You must run the SQL migration first!"
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  Open your Supabase Dashboard"
echo "   → Go to: https://supabase.com/dashboard"
echo ""
echo "2️⃣  Select your project (EAS_AI_Dashboard)"
echo ""
echo "3️⃣  Go to SQL Editor"
echo "   → Left sidebar → SQL Editor → New Query"
echo ""
echo "4️⃣  Copy the entire migration script:"
echo "   → File: sql/002_approval_workflow.sql"
echo ""
echo "5️⃣  Paste into the Supabase SQL Editor"
echo ""
echo "6️⃣  Click 'Run' button"
echo ""
echo "7️⃣  Wait for completion (should see green checkmark)"
echo ""
echo "8️⃣  Verify the tables were created:"
echo "   → Go to Database → Tables"
echo "   → Look for: submission_approvals, practice_spoc"
echo ""
echo "9️⃣  Once migration is complete, the approval workflow will work:"
echo "   ✓ Tasks will be routed to approval queue"
echo "   ✓ Admin Approvals tab will show pending tasks"
echo "   ✓ SPOCs will receive notifications"
echo "   ✓ Employees can track approval status"
echo ""
echo "❓ Need help?"
echo "   1. Check browser console (F12) for errors"
echo "   2. Verify all tables exist in Supabase"
echo "   3. Check RLS policies are enabled"
echo "   4. See docs/APPROVAL_WORKFLOW.md for details"
echo ""
